default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: root

development:
  <<: *default
  database: qpixel_dev

test:
  <<: *default
  database: qpixel_test

production:
  <<: *default
  database: qpixel