name: Dev Deploy
on:
  pull_request:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Copy key
      run: |
        echo ${{ secrets.DEV_DEPLOY_KEY }} > ~/deploy_key
    
    - name: Run SSH deploy command
      run: |
        ssh ubuntu@34.238.159.212 -i ~/deploy_key "cd /var/apps/qpixel ; bash -l ./deploy ${GITHUB_REF##*/}"
