name: Dev Deploy
on:
  pull_request:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: nelonoel/branch-name@v1
    - name: Set up SSH key
      run: |
        echo "${{ secrets.DEV_DEPLOY_KEY }}" > ~/deploy_key
        chmod 700 ~/deploy_key
    
    - name: Run SSH deploy command
      run: |
        ssh -i ~/deploy_key -o StrictHostKeyChecking=no ubuntu@dev.codidact.org "cd /var/apps/qpixel ; bash -l ./deploy ${BRANCH_NAME}"
