on:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://meta.codidact.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
